/**
 * Final-Core additive schema statements.
 *
 * These statements mirror canonical typed definitions in drizzle/schema.ts that
 * were never included in the historical runtime reconciliation list. They are
 * deliberately not registered as retrospective Drizzle history and are only
 * executed by a controlled, inspector-gated migration command.
 */
export const finalCoreAdditiveSchemaStatements = [
  String.raw`CREATE TABLE IF NOT EXISTS academyCurriculumSyncRuns (
    id int AUTO_INCREMENT NOT NULL,
    curriculumVersion varchar(40) NOT NULL,
    pathwaysProcessed int NOT NULL DEFAULT 0,
    lessonsProcessed int NOT NULL DEFAULT 0,
    validationErrors int NOT NULL DEFAULT 0,
    validationWarnings int NOT NULL DEFAULT 0,
    summaryJson text NOT NULL,
    createdAt timestamp NOT NULL DEFAULT (now()),
    CONSTRAINT academyCurriculumSyncRuns_id PRIMARY KEY(id)
  )`,
  String.raw`CREATE TABLE IF NOT EXISTS mediaAssets (
    id int AUTO_INCREMENT NOT NULL,
    tenantType varchar(50) NOT NULL DEFAULT 'individual',
    tenantId varchar(100) NOT NULL DEFAULT 'global',
    userId int,
    campaignId int,
    draftId varchar(40),
    jobId varchar(40),
    type varchar(30) NOT NULL DEFAULT 'other',
    provider varchar(50),
    task varchar(80),
    status varchar(30) NOT NULL DEFAULT 'created',
    localPath text,
    publicUrl text,
    thumbnailUrl text,
    mimeType varchar(120),
    fileSizeBytes int,
    durationSeconds int,
    width int,
    height int,
    generationPrompt text,
    generationSettingsJson text,
    outputMetadataJson text,
    errorMessage text,
    createdAt timestamp NOT NULL DEFAULT (now()),
    updatedAt timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT mediaAssets_id PRIMARY KEY(id)
  )`,
  String.raw`CREATE TABLE IF NOT EXISTS brandProfiles (
    id int AUTO_INCREMENT NOT NULL,
    tenantType varchar(50) NOT NULL DEFAULT 'individual',
    tenantId varchar(100) NOT NULL DEFAULT 'global',
    appKey varchar(80) NOT NULL DEFAULT 'equiprofile',
    name varchar(200) NOT NULL DEFAULT 'EquiProfile',
    brandVoice text,
    targetAudience text,
    positioning text,
    primaryCta varchar(200),
    prohibitedClaimsJson text,
    approvedClaimsJson text,
    colorsJson text,
    logoAssetId int,
    typographyJson text,
    hashtagStyle varchar(80),
    contentPillarsJson text,
    platformDefaultsJson text,
    createdAt timestamp NOT NULL DEFAULT (now()),
    updatedAt timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT brandProfiles_id PRIMARY KEY(id)
  )`,
  String.raw`CREATE TABLE IF NOT EXISTS brandAvatars (
    id int AUTO_INCREMENT NOT NULL,
    tenantType varchar(50) NOT NULL DEFAULT 'individual',
    tenantId varchar(100) NOT NULL DEFAULT 'global',
    workspaceId varchar(120) NOT NULL DEFAULT 'default',
    hostAppId varchar(120) NOT NULL DEFAULT 'equiprofile',
    brandProfileId int,
    brandKitId int,
    name varchar(200) NOT NULL,
    role varchar(120),
    visualDescription text,
    personality text,
    voiceStyle varchar(120),
    accent varchar(80),
    wardrobeRules text,
    backgroundRules text,
    referenceAssetId int,
    referenceAssetUrl text,
    promptTemplate text,
    negativePrompt text,
    consistencySeed varchar(80),
    preferredVoiceProfileId int,
    status varchar(20) NOT NULL DEFAULT 'active',
    createdAt timestamp NOT NULL DEFAULT (now()),
    updatedAt timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT brandAvatars_id PRIMARY KEY(id)
  )`,
  String.raw`CREATE TABLE IF NOT EXISTS growthProfiles (
    id int AUTO_INCREMENT NOT NULL,
    tenantType varchar(50) NOT NULL DEFAULT 'individual',
    tenantId varchar(100) NOT NULL DEFAULT 'global',
    brandProfileId int,
    targetPlatformsJson text,
    growthGoal text,
    audienceDescription text,
    postingCadenceJson text,
    conversionGoal text,
    preferredContentTypesJson text,
    bestPerformingHooksJson text,
    bestPostingWindowsJson text,
    notes text,
    createdAt timestamp NOT NULL DEFAULT (now()),
    updatedAt timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT growthProfiles_id PRIMARY KEY(id)
  )`,
  String.raw`CREATE TABLE IF NOT EXISTS contentScores (
    id int AUTO_INCREMENT NOT NULL,
    draftId varchar(40),
    assetId int,
    platform varchar(80),
    hookScore int,
    platformFitScore int,
    conversionScore int,
    clarityScore int,
    complianceScore int,
    viralPotentialScore int,
    reasonsJson text,
    improvementSuggestionsJson text,
    createdAt timestamp NOT NULL DEFAULT (now()),
    CONSTRAINT contentScores_id PRIMARY KEY(id)
  )`,
  String.raw`CREATE TABLE IF NOT EXISTS platformStrategyRules (
    id int AUTO_INCREMENT NOT NULL,
    platform varchar(80) NOT NULL,
    version varchar(20) NOT NULL DEFAULT '1.0',
    rulesJson text,
    recommendedCadenceJson text,
    hookGuidelinesJson text,
    formatGuidelinesJson text,
    complianceNotesJson text,
    createdAt timestamp NOT NULL DEFAULT (now()),
    updatedAt timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT platformStrategyRules_id PRIMARY KEY(id)
  )`,
] as const;

export const finalCoreAdditiveSchemaTableNames = [
  "academyCurriculumSyncRuns",
  "mediaAssets",
  "brandProfiles",
  "brandAvatars",
  "growthProfiles",
  "contentScores",
  "platformStrategyRules",
] as const;
